### ISSUE TITLE
panicked at 'arithmetic operation overflowed'

### ISSUE THREAD

**Issue by vinipsmaker** [meqif/rust-utp#17]
This line: https://github.com/meqif/rust-utp/blob/88a3aa6410f52eac1a228790c4297b650c1d3274/src/socket.rs#L506

More info: https://github.com/maidsafe/crust/issues/372

We've ran into 'arithmetic operation overflowed' from rust-utp before (just needed to let it execute longe enough), but the new rendezvous code we added started to show the problem much more frequently.

**Comment by meqif** [comment]
Thank you for the bug report, it should be fixed now. I've been meaning to fix this particular bug.

**Comment by inetic** [comment]
Thanks @meqif, I was going to do the same, and funny fact is that the code is almost identical. Though are you sure it is the correct solution? I have a feeling that originally the arithmetic overflow was intentional, otherwise we're losing the 1 bit sign information.

I'm currently trying to find out how it is done in libutp, and [this is](https://github.com/bittorrent/libutp/blob/master/utp_internal.cpp#L1985) as far as I got.

**Comment by meqif** [comment]
I'm reasonably sure it is the right solution, but I might be wrong.

As I understand it, what matters in LEDBAT (µTP's congestion control algorithm) is the magnitude of the delay between the peers, not so much its sign/direction.

The line you mentioned shows that libutp also uses an _unsigned_ integer (`u32`) for the delay, which suggests they also don't care about the sign, only the absolute difference between the timestamps. I think it's weird that they ignore the possibility of overflow, though.

**Comment by inetic** [comment]
There is one more `arithmetic operation overflowed` here:

https://github.com/meqif/rust-utp/blob/12e9a00fb270f90c7943cdaa60b2a7665461095b/src/socket.rs#L413

Sorry to not have included it before, I lost the line and couldn't find it. I'll create a PR if you don't beat me to it (currently have to work on something else).

Thanks

**Comment by meqif** [comment]
That's weird, that one isn't supposed to ever overflow, unless there's something weird going on with `now_microseconds`. It should be fixed in https://github.com/meqif/rust-utp/commit/234eb6214c845cd134ef4cbdc8e6f14d54269efe.

**Comment by inetic** [comment]
Yeah, it's weird, perhaps the `time::get_time` function isn't [steady](http://en.cppreference.com/w/cpp/chrono/steady_clock).

**Comment by meqif** [comment]
That's a good point, thank you for raising it. https://github.com/meqif/rust-utp/commit/da1a05f0056a28b90724ffd1c79385c792f349ac uses `time::SteadyClock`.
