### ISSUE TITLE
Unable to concurrently send and receive without racing

### ISSUE THREAD

**Issue by ned14** [meqif/rust-utp#2]
We're trying to use rust-utp in https://github.com/maidsafe/crust but we have the problem that we need to send data whilst also concurrently waiting for new data to arrive. The obvious fix is a mutex per UtpSocket which is unlocked while udpsocket.recv_from() to allow sends and other operations to run.

If you're not able to do it yourself promptly, would you be interested in a pull request, or is there a better way than the above?

Thanks,
Niall

**Comment by ned14** [comment]
Actually scratch this issue, it would seem you want TWO UtpSockets because either a socket is bound and listening OR it is connected and sending. I personally would prefer if you had named them differently as a result, but ok I think I'm on the right page now.

**Comment by meqif** [comment]
> but we have the problem that we need to send data whilst also concurrently waiting for new data to arrive.

I agree that there's a serious limitation in that aspect. Would something similar to `TcpListener` be useful for your particular use case? I pushed very recently a `UtpListener` implementation along the same lines as `TcpListener`, and a simple echo server example to master, perhaps you'll find it useful.

Unfortunately, I'm somewhat busy, so I probably won't be able make large changes right away.

**Comment by ned14** [comment]
Thanks for the UtpListener push.

It still makes things a bit tricky here, because right now crust has no notion of changing how it talks to a remote peer after a connection is established. I'll look into getting crust to do a ping after initial connect to discover the newly accepted port, no reason that shouldn't work.
